{*
 *  Tous droits réservés NDKDESIGN
 *
 *  @author Hendrik Masson <postmaster@ndk-design.fr>
 *  @copyright Copyright 2013 - 2014 Hendrik Masson
 *  @license   Tous droits réservés
*}

<div class="panel">
	<h3><i class="icon icon-edit"></i> {l s='Ndk Advanced Customization Fields' mod='ndk_advanced_custom_fields'}</h3>
	<br/>
	<h4><i class="icon icon-tags"></i> {l s='Purge unused customization' mod='ndk_advanced_custom_fields'}</h4>
	<p>
		{l s='Here is an url to purge unused customization' mod='ndk_advanced_custom_fields'} <br/>
		{l s='It will delete products and customization generated by module, which have not been ordered, and older than 5 days' mod='ndk_advanced_custom_fields'}<br/>
		{l s='You can add it to your crontab to automate the process' mod='ndk_advanced_custom_fields'}
		<a class="button" target="_blank" href="{$base_url|escape:'htmlall':'UTF-8'}/modules/ndk_advanced_custom_fields/purgeVirtualsProducts.php">{$base_url|escape:'htmlall':'UTF-8'}/modules/ndk_advanced_custom_fields/purgeVirtualsProducts.php</a>
	</p>
	<br/><br/>
	
	{if $message}
		{foreach $message as $msg}{$msg}{/foreach}
	{/if}
</div>


